name: Deploy to monday code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to monday code
        uses: mondaycom/monday-code-deploy-action@master
        with:
          token: ${{ secrets.MONDAY_TOKEN }}
          appId: 10107540
